<?php

/**
 * @file
 * Hooks and API for the islandora_job_module.
 */

const ISLANDORA_JOB_STATE__ERROR = -1;
const ISLANDORA_JOB_STATE__WAITING = 0;
const ISLANDORA_JOB_STATE__RUNNING = 1;

/**
 * Implements hook_menu().
 */
function islandora_job_menu() {
  $items = array();
  $items['admin/islandora/tools/job'] = array(
    'title' => 'Islandora Job',
    'description' => 'Configuration page for the Islandora Job module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_job_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
  );
  return $items;
}

/**
 * Runs a job in the foreground.
 *
 * Returns the result of the job to the requesting code. All parameters other
 * than the job name are considered arguments for the job.  Arguments get
 * JSON encoded as an array.
 *
 * @param string $job_name
 *   Name of the job to run.
 *
 * @return string|bool
 *   The result of the job or FALSE if it was not queued for duping.
 */
function islandora_job_submit($job_name) {
  module_load_include('inc', 'islandora_job', 'includes/utilities');
  module_load_include('inc', 'islandora_job', 'includes/db');
  $payload = islandora_job_format_payload($job_name, func_get_args());
  if (islandora_job_ensure_job_deduping($payload)) {
    $status_id = islandora_job_get_job_status_id($payload);
    try {
      module_invoke_all('islandora_job_started', $payload);
      $client = islandora_job_get_client();
      $job_handle = $client->doNormal(islandora_job_function_name($job_name), $payload);
      if ($client->returnCode() != GEARMAN_SUCCESS) {
        islandora_job_remove_job_status($status_id);
        return FALSE;
      }
      return $job_handle;
    }
    catch (Exception $e) {
      islandora_job_remove_job_status($status_id);
    }
  }
}

/**
 * Runs a job in the background.
 *
 * The result is never returned to the requesting code. All parameters other
 * than the job name are considered arguments for the job.  Arguments get
 * JSON encoded as an array.
 *
 * @param string $job_name
 *   Name of the job to run.
 *
 * @return string|bool
 *   The job handle or FALSE if it was not queued.
 */
function islandora_job_submit_background($job_name) {
  module_load_include('inc', 'islandora_job', 'includes/utilities');
  module_load_include('inc', 'islandora_job', 'includes/db');
  $payload = islandora_job_format_payload($job_name, func_get_args());
  if (islandora_job_ensure_job_deduping($payload)) {
    $status_id = islandora_job_get_job_status_id($payload);
    try {
      module_invoke_all('islandora_job_started', $payload);
      $client = islandora_job_get_client();
      $job_handle = $client->doBackground(islandora_job_function_name($job_name), $payload);
      if ($client->returnCode() != GEARMAN_SUCCESS) {
        islandora_job_remove_job_status($status_id);
        return FALSE;
      }
      return $job_handle;
    }
    catch (Exception $e) {
      islandora_job_remove_job_status($status_id);
    }
  }
  return FALSE;
}

/**
 * Runs multiple jobs with as much concurrency as possible.
 *
 * Blocks until all are complete.
 *
 * @param array $tasks
 *   Contains any number of entries that look like this:
 *   [
 *     'job_name' => 'my_sweet_job_function',
 *     'args' => array('herp', 'derp'),
 *   ].
 * @param callable $callback
 *   A callback for when each task is completed.  See
 *   http://php.net/manual/en/gearmanclient.setcompletecallback.php
 *   and http://gearman.org/examples/multi-query/ for more.
 *
 * @return bool
 *   TRUE on success.
 */
function islandora_job_submit_batch(array $tasks, $callback = NULL) {
  module_load_include('inc', 'islandora_job', 'includes/utilities');
  $client = islandora_job_get_client();
  if (!is_null($callback)) {
    $client->setCompleteCallback($callback);
  }
  foreach ($tasks as $task) {
    $job_name = $task['job_name'];
    $args = $task['args'];
    // Push on a dummy arg as if this array came from func_get_args().
    array_unshift($args, '');
    $payload = islandora_job_format_payload($job_name, $args);
    $client->addTask(islandora_job_function_name($job_name), $payload);
  }
  return $client->runTasks();
}
