<?php

/**
 * @file
 * Main hooks for islandora_job_jobs.
 */

/**
 * Implements hook_islandora_job_register_jobs().
 */
function islandora_job_jobs_islandora_job_register_jobs() {
  return array(
    'islandora_job_jobs_islandora_do_derivatives' => array(
      'type' => 'inc',
      'module' => 'islandora_job_jobs',
      'name' => 'includes/wrappers',
      'alias' => 'ijj-d',
    ),
  );
}

/**
 * Implements hook_form_islandora_job_admin_form_alter().
 */
function islandora_job_jobs_form_islandora_job_admin_form_alter(&$form, &$form_state) {
  form_load_include($form_state, 'inc', 'islandora_job_jobs', 'includes/utilities');
  $form['islandora_job_jobs_derivatives_idle_wait'] = array(
    '#type' => 'textfield',
    '#title' => t('Derivative idle time'),
    '#description' => t('An amount of time in seconds required to pass before being handled by Gearman. Set to 0 to disable.'),
    '#default_value' => variable_get('islandora_job_jobs_derivatives_idle_wait', '10'),
    '#required' => TRUE,
    '#element_validate' => array(
      'islandora_job_jobs_element_validate_integer_positive_or_zero',
    ),
  );
  $conditions = array(
    ':input[name="islandora_job_jobs_derivatives_idle_wait"]' => array(
      '!value' => '0',
    ),
  );
  $form['islandora_job_jobs_derivative_requeues'] = array(
    '#type' => 'textfield',
    '#title' => t('Derivative requeues'),
    '#description' => t('After the object has been requeued this many times, we will force it to be processed.'),
    '#default_value' => variable_get('islandora_job_jobs_derivative_requeues', 3),
    '#element_validate' => array(
      'element_validate_integer_positive',
    ),
    '#states' => array(
      'visible' => $conditions,
      'required' => $conditions,
    ),
  );
  $form['islandora_job_jobs_derivatives_idle_wait_requeue_opt'] = array(
    '#type' => 'checkbox',
    '#title' => t('Requeue optimization'),
    '#description' => t('Immediately requeue first entrance under the time limit, ideally making way for other jobs which may be processable.'),
    '#default_value' => variable_get('islandora_job_jobs_derivatives_idle_wait_requeue_opt', TRUE),
    '#states' => array(
      'visible' => $conditions,
    ),
  );
  $form['islandora_job_jobs_derivatives_idle_wait_no_requeue'] = array(
    '#type' => 'checkbox',
    '#title' => t('Skip requeue after sleep'),
    '#description' => t('Subsequent requeues after the first typically sleep to try to wait for the object to become idle requeuing to start testing again.'),
    '#default_value' => variable_get('islandora_job_jobs_derivatives_idle_wait_no_requeue', FALSE),
    '#states' => array(
      'visible' => $conditions,
    ),
  );
  $form['#validate'][] = 'islandora_job_jobs_islandora_job_admin_form_validate';
  return $form;
}
