<?php

/**
 * @file
 * Main hook implementations.
 */

/**
 * Implements hook_islandora_object_ingested().
 */
function islandora_job_derivatives_islandora_object_ingested(AbstractObject $object) {
  module_load_include('inc', 'islandora', 'includes/derivatives');
  if (islandora_get_defer_derivatives_flag($object)) {
    islandora_job_submit_background('islandora_job_jobs_islandora_do_derivatives', $object->id, array());
  }
}

/**
 * Implements hook_islandora_datastream_ingested().
 */
function islandora_job_derivatives_islandora_datastream_ingested(AbstractObject $object, AbstractDatastream $datastream) {
  dd("islandora_job_derivatives_islandora_datastream_ingested");
  dd($object->id);
  dd($datastream->id);
  $trace = debug_backtrace();
  foreach ($trace as $trace_frame) {
    if (isset($trace_frame['function']) && $trace_frame['function'] == 'ingestObject') {
      dd("ingestObject");
      return;
    }
  }
  $options = array();
  $options['source_dsid'] = $datastream->id;
  islandora_job_submit_background('islandora_job_jobs_islandora_do_derivatives', $object->id, $options);
}
