<?php

/**
 * @file
 * Main hook implementations.
 */

/**
 * Implements hook_islandora_object_ingested().
 */
function islandora_job_derivatives_islandora_object_ingested(AbstractObject $object) {
  module_load_include('inc', 'islandora', 'includes/derivatives');
  if (islandora_get_defer_derivatives_flag($object)) {
    islandora_job_submit_background('islandora_job_jobs_islandora_do_derivatives', $object->id, array());
  }
}
